const LANGUAGES = {
    sw: { name: "Kiswahili", flag: "🇰🇪", greeting: "Jambo!" },
    ki: { name: "Gikuyu", flag: "🏔️", greeting: "Wake!" },
    lu: { name: "Dholuo", flag: "🐟", greeting: "Nyalore!" },
    ka: { name: "Kikamba", flag: "🌄", greeting: "Wathi!" },
    gu: { name: "Ekegusii", flag: "🌿", greeting: "Mogetsia!" },
    kl: { name: "Kalenjin", flag: "🏃", greeting: "Chamgei!" },
    lh: { name: "Oluluyia", flag: "🌳", greeting: "Woye!" },
    me: { name: "Kimeru", flag: "⛰️", greeting: "Nio!" },
    ma: { name: "Maa", flag: "🦁", greeting: "Supai!" },
    so: { name: "Af-Soomaali", flag: "🐪", greeting: "Salama!" }
};

const WORDS = {
    sw: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ng'ombe" },
            { emoji: "🐐", english: "Goat", local: "Mbuzi" },
            { emoji: "🐔", english: "Chicken", local: "Kuku" },
            { emoji: "🐕", english: "Dog", local: "Mbwa" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Kondoo" },
            { emoji: "🐴", english: "Horse", local: "Farasi" },
            { emoji: "🐟", english: "Fish", local: "Samaki" },
            { emoji: "🐘", english: "Elephant", local: "Tembo" },
            { emoji: "🦁", english: "Lion", local: "Simba" },
            { emoji: "🐊", english: "Crocodile", local: "Mamba" },
            { emoji: "🐒", english: "Monkey", local: "Tumbili" },
            { emoji: "🦅", english: "Eagle", local: "Tai" },
            { emoji: "🐍", english: "Snake", local: "Nyoka" },
            { emoji: "🐸", english: "Frog", local: "Chura" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Wali" },
            { emoji: "🌽", english: "Maize", local: "Mahindi" },
            { emoji: "🫘", english: "Beans", local: "Maharage" },
            { emoji: "🥔", english: "Potato", local: "Viazi" },
            { emoji: "🍌", english: "Banana", local: "Ndizi" },
            { emoji: "🥭", english: "Mango", local: "Embe" },
            { emoji: "🥑", english: "Avocado", local: "Parachichi" },
            { emoji: "🍊", english: "Orange", local: "Chungwa" },
            { emoji: "🍉", english: "Watermelon", local: "Tikiti" },
            { emoji: "🥛", english: "Milk", local: "Maziwa" },
            { emoji: "🍞", english: "Bread", local: "Mkate" },
            { emoji: "🥚", english: "Egg", local: "Yai" },
            { emoji: "🥩", english: "Meat", local: "Nyama" },
            { emoji: "🥜", english: "Groundnuts", local: "Njugu" },
            { emoji: "🥬", english: "Vegetables", local: "Mboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Baba" },
            { emoji: "👩", english: "Mother", local: "Mama" },
            { emoji: "👦", english: "Boy", local: "Mtoto wa kiume" },
            { emoji: "👧", english: "Girl", local: "Mtoto wa kike" },
            { emoji: "👴", english: "Grandfather", local: "Babu" },
            { emoji: "👵", english: "Grandmother", local: "Bibi" },
            { emoji: "👨‍👦", english: "Brother", local: "Kaka" },
            { emoji: "👩‍👧", english: "Sister", local: "Dada" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Familia" },
            { emoji: "👶", english: "Baby", local: "Mtoto" },
            { emoji: "🧑", english: "Person", local: "Mtu" },
            { emoji: "👫", english: "Friends", local: "Marafiki" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Mwalimu" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Mpishi" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Nyekundu" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Kijani" },
            { emoji: "🟡", english: "Yellow", local: "Njano" },
            { emoji: "🟠", english: "Orange", local: "Machungwa" },
            { emoji: "🟣", english: "Purple", local: "Zambarau" },
            { emoji: "⚫", english: "Black", local: "Nyeusi" },
            { emoji: "⚪", english: "White", local: "Nyeupe" },
            { emoji: "🟤", english: "Brown", local: "Kahawia" },
            { emoji: "💗", english: "Pink", local: "Waridi" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Moja" },
            { emoji: "2️⃣", english: "Two", local: "Mbili" },
            { emoji: "3️⃣", english: "Three", local: "Tatu" },
            { emoji: "4️⃣", english: "Four", local: "Nne" },
            { emoji: "5️⃣", english: "Five", local: "Tano" },
            { emoji: "6️⃣", english: "Six", local: "Sita" },
            { emoji: "7️⃣", english: "Seven", local: "Saba" },
            { emoji: "8️⃣", english: "Eight", local: "Nane" },
            { emoji: "9️⃣", english: "Nine", local: "Tisa" },
            { emoji: "🔟", english: "Ten", local: "Kumi" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Jicho" },
            { emoji: "👂", english: "Ear", local: "Sikio" },
            { emoji: "👃", english: "Nose", local: "Pua" },
            { emoji: "👄", english: "Mouth", local: "Mdomo" },
            { emoji: "🦷", english: "Tooth", local: "Jino" },
            { emoji: "✋", english: "Hand", local: "Mkono" },
            { emoji: "🦶", english: "Foot", local: "Mguu" },
            { emoji: "💇", english: "Hair", local: "Nywele" },
            { emoji: "🧠", english: "Head", local: "Kichwa" },
            { emoji: "❤️", english: "Heart", local: "Moyo" }
        ]
    },
    ki: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ng'ombe" },
            { emoji: "🐐", english: "Goat", local: "Mburi" },
            { emoji: "🐔", english: "Chicken", local: "Kuku" },
            { emoji: "🐕", english: "Dog", local: "Induku" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "绪绪" },
            { emoji: "🐴", english: "Horse", local: "Harasi" },
            { emoji: "🐟", english: "Fish", local: "Raı" },
            { emoji: "🐘", english: "Elephant", local: "Njogu" },
            { emoji: "🦁", english: "Lion", local: "Harara" },
            { emoji: "🐊", english: "Crocodile", local: "Mamba" },
            { emoji: "🐒", english: "Monkey", local: "Hostu" },
            { emoji: "🦅", english: "Eagle", local: "Nungu" },
            { emoji: "🐍", english: "Snake", local: "Noka" },
            { emoji: "🐸", english: "Frog", local: "Thingiti" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Mwoko" },
            { emoji: "🌽", english: "Maize", local: "Muhoi" },
            { emoji: "🫘", english: "Beans", local: "Nyoũ" },
            { emoji: "🥔", english: "Potato", local: "Irĩa" },
            { emoji: "🍌", english: "Banana", local: "Mũgũnda" },
            { emoji: "🥭", english: "Mango", local: "Mũembe" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Chungwa" },
            { emoji: "🍉", english: "Watermelon", local: "Watermelon" },
            { emoji: "🥛", english: "Milk", local: "Rīrĩa" },
            { emoji: "🍞", english: "Bread", local: "Mugate" },
            { emoji: "🥚", english: "Egg", local: "Lĩhĩ" },
            { emoji: "🥩", english: "Meat", local: "Nyama" },
            { emoji: "🥜", english: "Groundnuts", local: "Ngroundu" },
            { emoji: "🥬", english: "Vegetables", local: "Mboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Baba" },
            { emoji: "👩", english: "Mother", local: "Maitu" },
            { emoji: "👦", english: "Boy", local: "Mũthondeki" },
            { emoji: "👧", english: "Girl", local: "Mũtheri" },
            { emoji: "👴", english: "Grandfather", local: "Gũkũũ" },
            { emoji: "👵", english: "Grandmother", local: "ũtheri" },
            { emoji: "👨‍👦", english: "Brother", local: "Mũkũũ" },
            { emoji: "👩‍👧", english: "Sister", local: "Mũthondeki" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Mũthenya" },
            { emoji: "👶", english: "Baby", local: "Mũthondeki" },
            { emoji: "🧑", english: "Person", local: "Mũndũ" },
            { emoji: "👫", english: "Friends", local: "Atinga" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Mũthangĩ" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Mũthũrĩrĩ" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Mũthĩmũ" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Mũhĩrĩ" },
            { emoji: "🟡", english: "Yellow", local: "Kĩthĩthĩ" },
            { emoji: "🟠", english: "Orange", local: "Machungwa" },
            { emoji: "🟣", english: "Purple", local: "Zambarau" },
            { emoji: "⚫", english: "Black", local: "Mũgũ" },
            { emoji: "⚪", english: "White", local: "Wĩra" },
            { emoji: "🟤", english: "Brown", local: "Kahawia" },
            { emoji: "💗", english: "Pink", local: "Waridi" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Ĩmwe" },
            { emoji: "2️⃣", english: "Two", local: "Ĩrĩ" },
            { emoji: "3️⃣", english: "Three", local: "Ĩtatu" },
            { emoji: "4️⃣", english: "Four", local: "Ĩnne" },
            { emoji: "5️⃣", english: "Five", local: "ĩtano" },
            { emoji: "6️⃣", english: "Six", local: "Ĩtandatu" },
            { emoji: "7️⃣", english: "Seven", local: "Ĩnje" },
            { emoji: "8️⃣", english: "Eight", local: "Ĩnane" },
            { emoji: "9️⃣", english: "Nine", local: "Ĩcũma" },
            { emoji: "🔟", english: "Ten", local: "Ĩkũmi" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Irio" },
            { emoji: "👂", english: "Ear", local: "Thĩĩ" },
            { emoji: "👃", english: "Nose", local: "Gĩkũũ" },
            { emoji: "👄", english: "Mouth", local: "Kĩa" },
            { emoji: "🦷", english: "Tooth", local: "Ndira" },
            { emoji: "✋", english: "Hand", local: "Elĩ" },
            { emoji: "🦶", english: "Foot", local: "Guoka" },
            { emoji: "💇", english: "Hair", local: "Gĩthaka" },
            { emoji: "🧠", english: "Head", local: "Rĩĩ" },
            { emoji: "❤️", english: "Heart", local: "Mutwe" }
        ]
    },
    lu: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Chang' " },
            { emoji: "🐐", english: "Goat", local: "Ng'atì" },
            { emoji: "🐔", english: "Chicken", local: "Kok" },
            { emoji: "🐕", english: "Dog", local: "Wier" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Embà" },
            { emoji: "🐴", english: "Horse", local: "Kadìì" },
            { emoji: "🐟", english: "Fish", local: "Ngeso" },
            { emoji: "🐘", english: "Elephant", local: "Ngiro" },
            { emoji: "🦁", english: "Lion", local: "Otieno" },
            { emoji: "🐊", english: "Crocodile", local: "Yiech" },
            { emoji: "🐒", english: "Monkey", local: "Ogoki" },
            { emoji: "🦅", english: "Eagle", local: "Enyàmà" },
            { emoji: "🐍", english: "Snake", local: "Ndiya" },
            { emoji: "🐸", english: "Frog", local: "Kiyasi" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Wàlì" },
            { emoji: "🌽", english: "Maize", local: "Kadongo" },
            { emoji: "🫘", english: "Beans", local: "Nyahà" },
            { emoji: "🥔", english: "Potato", local: "Àpàng" },
            { emoji: "🍌", english: "Banana", local: "Bogwe" },
            { emoji: "🥭", english: "Mango", local: "Ómbe" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tìkì" },
            { emoji: "🥛", english: "Milk", local: "Kàmà" },
            { emoji: "🍞", english: "Bread", local: "Mugate" },
            { emoji: "🥚", english: "Egg", local: "Nyinga" },
            { emoji: "🥩", english: "Meat", local: "Enyàmà" },
            { emoji: "🥜", english: "Groundnuts", local: "Groundnut" },
            { emoji: "🥬", english: "Vegetables", local: "Mboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Chuà" },
            { emoji: "👩", english: "Mother", local: "Mama" },
            { emoji: "👦", english: "Boy", local: "Wuodi" },
            { emoji: "👧", english: "Girl", local: "Nyàr" },
            { emoji: "👴", english: "Grandfather", local: "Baba" },
            { emoji: "👵", english: "Grandmother", local: "Baba" },
            { emoji: "👨‍👦", english: "Brother", local: "Ratego" },
            { emoji: "👩‍👧", english: "Sister", local: "Nyàr" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Chin" },
            { emoji: "👶", english: "Baby", local: "Chiëch" },
            { emoji: "🧑", english: "Person", local: "Jàr" },
            { emoji: "👫", english: "Friends", local: "Màyàw" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Nyàsàlè" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Odëg" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Yiero" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Aboro" },
            { emoji: "🟡", english: "Yellow", local: "Opòpò" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Mach" },
            { emoji: "⚪", english: "White", local: "Wuyo" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Achol" },
            { emoji: "2️⃣", english: "Two", local: "Ariyo" },
            { emoji: "3️⃣", english: "Three", local: "Adek" },
            { emoji: "4️⃣", english: "Four", local: "Angwen" },
            { emoji: "5️⃣", english: "Five", local: "Abich" },
            { emoji: "6️⃣", english: "Six", local: "Kàsìt" },
            { emoji: "7️⃣", english: "Seven", local: "Kàbèdò" },
            { emoji: "8️⃣", english: "Eight", local: "Kàbèdò na achol" },
            { emoji: "9️⃣", english: "Nine", local: "Ochol" },
            { emoji: "🔟", english: "Ten", local: "Tok" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Ida" },
            { emoji: "👂", english: "Ear", local: "Pinè" },
            { emoji: "👃", english: "Nose", local: "Dìì" },
            { emoji: "👄", english: "Mouth", local: "Ochieng" },
            { emoji: "🦷", english: "Tooth", local: "Pìyò" },
            { emoji: "✋", english: "Hand", local: "Lwenyo" },
            { emoji: "🦶", english: "Foot", local: "Gòk" },
            { emoji: "💇", english: "Hair", local: "Owino" },
            { emoji: "🧠", english: "Head", local: "Wich" },
            { emoji: "❤️", english: "Heart", local: "Yath" }
        ]
    },
    ka: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ng'ombe" },
            { emoji: "🐐", english: "Goat", local: "Mbũũ" },
            { emoji: "🐔", english: "Chicken", local: "Kuku" },
            { emoji: "🐕", english: "Dog", local: "Waã" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Ngoi" },
            { emoji: "🐴", english: "Horse", local: "Faraasi" },
            { emoji: "🐟", english: "Fish", local: "Syũũ" },
            { emoji: "🐘", english: "Elephant", local: "Tãũ" },
            { emoji: "🦁", english: "Lion", local: "Ìĩ" },
            { emoji: "🐊", english: "Crocodile", local: "Keũ" },
            { emoji: "🐒", english: "Monkey", local: "Kivii" },
            { emoji: "🦅", english: "Eagle", local: "Ngwĩtũ" },
            { emoji: "🐍", english: "Snake", local: "Mũsyũ" },
            { emoji: "🐸", english: "Frog", local: "Nzou" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Mũhõ" },
            { emoji: "🌽", english: "Maize", local: "Mũhũũ" },
            { emoji: "🫘", english: "Beans", local: "Nzoo" },
            { emoji: "🥔", english: "Potato", local: "Irio" },
            { emoji: "🍌", english: "Banana", local: "Ndũũ" },
            { emoji: "🥭", english: "Mango", local: "Mũũ" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tii" },
            { emoji: "🥛", english: "Milk", local: "Mãĩ" },
            { emoji: "🍞", english: "Bread", local: "Mũgathe" },
            { emoji: "🥚", english: "Egg", local: "Mãhĩ" },
            { emoji: "🥩", english: "Meat", local: "Nyama" },
            { emoji: "🥜", english: "Groundnuts", local: "Groundnut" },
            { emoji: "🥬", english: "Vegetables", local: "Mboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Baba" },
            { emoji: "👩", english: "Mother", local: "Waa" },
            { emoji: "👦", english: "Boy", local: "Mwana" },
            { emoji: "👧", english: "Girl", local: "Mwana" },
            { emoji: "👴", english: "Grandfather", local: "Tãtã" },
            { emoji: "👵", english: "Grandmother", local: "Tũũtũ" },
            { emoji: "👨‍👦", english: "Brother", local: "Mũũi" },
            { emoji: "👩‍👧", english: "Sister", local: "Mũũi" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Mũũi" },
            { emoji: "👶", english: "Baby", local: "Mwana" },
            { emoji: "🧑", english: "Person", local: "Mũũni" },
            { emoji: "👫", english: "Friends", local: "Asoi" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Mũũthangĩ" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Mũũthũũ" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Mũu" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Mũhĩĩ" },
            { emoji: "🟡", english: "Yellow", local: "Kĩthii" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Mũũ" },
            { emoji: "⚪", english: "White", local: "Wĩra" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Ĩmwe" },
            { emoji: "2️⃣", english: "Two", local: "Ĩĩ" },
            { emoji: "3️⃣", english: "Three", local: "Ĩtatu" },
            { emoji: "4️⃣", english: "Four", local: "Ĩnne" },
            { emoji: "5️⃣", english: "Five", local: "Ĩtano" },
            { emoji: "6️⃣", english: "Six", local: "Ĩtaa" },
            { emoji: "7️⃣", english: "Seven", local: "Ĩnje" },
            { emoji: "8️⃣", english: "Eight", local: "Ĩnane" },
            { emoji: "9️⃣", english: "Nine", local: "Ĩcũũma" },
            { emoji: "🔟", english: "Ten", local: "Ĩkũũmi" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Ĩtwe" },
            { emoji: "👂", english: "Ear", local: "Thii" },
            { emoji: "👃", english: "Nose", local: "Gĩkũũ" },
            { emoji: "👄", english: "Mouth", local: "Kĩa" },
            { emoji: "🦷", english: "Tooth", local: "Ndira" },
            { emoji: "✋", english: "Hand", local: "Moko" },
            { emoji: "🦶", english: "Foot", local: "Guuka" },
            { emoji: "💇", english: "Hair", local: "Mĩtwe" },
            { emoji: "🧠", english: "Head", local: "Rĩĩ" },
            { emoji: "❤️", english: "Heart", local: "Mũtwe" }
        ]
    },
    gu: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ontumu" },
            { emoji: "🐐", english: "Goat", local: "Iburi" },
            { emoji: "🐔", english: "Chicken", local: "Kuku" },
            { emoji: "🐕", english: "Dog", local: "Isira" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Ontondu" },
            { emoji: "🐴", english: "Horse", local: "Farasi" },
            { emoji: "🐟", english: "Fish", local: "Enanda" },
            { emoji: "🐘", english: "Elephant", local: "Enkoromoitio" },
            { emoji: "🦁", english: "Lion", local: "Omotune" },
            { emoji: "🐊", english: "Crocodile", local: "Enyangi" },
            { emoji: "🐒", english: "Monkey", local: "Etemo" },
            { emoji: "🦅", english: "Eagle", local: "Omotundi" },
            { emoji: "🐍", english: "Snake", local: "Ondieche" },
            { emoji: "🐸", english: "Frog", local: "Enyanyi" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Omosi" },
            { emoji: "🌽", english: "Maize", local: "Omagere" },
            { emoji: "🫘", english: "Beans", local: "Egenda" },
            { emoji: "🥔", english: "Potato", local: "Obia" },
            { emoji: "🍌", english: "Banana", local: "Eketi" },
            { emoji: "🥭", english: "Mango", local: "Embe" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tiki" },
            { emoji: "🥛", english: "Milk", local: "Amaraba" },
            { emoji: "🍞", english: "Bread", local: "Mogate" },
            { emoji: "🥚", english: "Egg", local: "Emai" },
            { emoji: "🥩", english: "Meat", local: "Enyama" },
            { emoji: "🥜", english: "Groundnuts", local: "Groundnut" },
            { emoji: "🥬", english: "Vegetables", local: "Emboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Baba" },
            { emoji: "👩", english: "Mother", local: "Maya" },
            { emoji: "👦", english: "Boy", local: "Morane" },
            { emoji: "👧", english: "Girl", local: "Mokore" },
            { emoji: "👴", english: "Grandfather", local: "Goka" },
            { emoji: "👵", english: "Grandmother", local: "Ogori" },
            { emoji: "👨‍👦", english: "Brother", local: "Mourane" },
            { emoji: "👩‍👧", english: "Sister", local: "Mokore" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Abana" },
            { emoji: "👶", english: "Baby", local: "Akarina" },
            { emoji: "🧑", english: "Person", local: "Omogusi" },
            { emoji: "👫", english: "Friends", local: "Abantani" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Omouretani" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Omouregi" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Redio" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Buluu" },
            { emoji: "🟡", english: "Yellow", local: "Rang'i" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Amakara" },
            { emoji: "⚪", english: "White", local: "Gwencha" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Ringi" },
            { emoji: "2️⃣", english: "Two", local: "Riri" },
            { emoji: "3️⃣", english: "Three", local: "Garu" },
            { emoji: "4️⃣", english: "Four", local: "Kane" },
            { emoji: "5️⃣", english: "Five", local: "Tano" },
            { emoji: "6️⃣", english: "Six", local: "Monto" },
            { emoji: "7️⃣", english: "Seven", local: "Nkombo" },
            { emoji: "8️⃣", english: "Eight", local: "Sane" },
            { emoji: "9️⃣", english: "Nine", local: "Soko" },
            { emoji: "🔟", english: "Ten", local: "Aramu" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Icho" },
            { emoji: "👂", english: "Ear", local: "Gotho" },
            { emoji: "👃", english: "Nose", local: "Guka" },
            { emoji: "👄", english: "Mouth", local: "Amagongo" },
            { emoji: "🦷", english: "Tooth", local: "Enta" },
            { emoji: "✋", english: "Hand", local: "Okoocha" },
            { emoji: "🦶", english: "Foot", local: "Ogwe" },
            { emoji: "💇", english: "Hair", local: "Enyancha" },
            { emoji: "🧠", english: "Head", local: "Otumia" },
            { emoji: "❤️", english: "Heart", local: "Omutima" }
        ]
    },
    kl: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ewet" },
            { emoji: "🐐", english: "Goat", local: "Goiyo" },
            { emoji: "🐔", english: "Chicken", local: "Kok" },
            { emoji: "🐕", english: "Dog", local: "Owuar" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Poiyet" },
            { emoji: "🐴", english: "Horse", local: "Horisi" },
            { emoji: "🐟", english: "Fish", local: "Amiet" },
            { emoji: "🐘", english: "Elephant", local: "Ngirotich" },
            { emoji: "🦁", english: "Lion", local: "Oltumurei" },
            { emoji: "🐊", english: "Crocodile", local: "Keiyo" },
            { emoji: "🐒", english: "Monkey", local: "Engikaret" },
            { emoji: "🦅", english: "Eagle", local: "Oiyo" },
            { emoji: "🐍", english: "Snake", local: "Engikaret" },
            { emoji: "🐸", english: "Frog", local: "Endulei" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Wali" },
            { emoji: "🌽", english: "Maize", local: "Endulei" },
            { emoji: "🫘", english: "Beans", local: "Gunde" },
            { emoji: "🥔", english: "Potato", local: "Oiyo" },
            { emoji: "🍌", english: "Banana", local: "Endulei" },
            { emoji: "🥭", english: "Mango", local: "Mango" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tiki" },
            { emoji: "🥛", english: "Milk", local: "Kamut" },
            { emoji: "🍞", english: "Bread", local: "Mugat" },
            { emoji: "🥚", english: "Egg", local: "Oiyo" },
            { emoji: "🥩", english: "Meat", local: "Engata" },
            { emoji: "🥜", english: "Groundnuts", local: "Gunde" },
            { emoji: "🥬", english: "Vegetables", local: "Emboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Ata" },
            { emoji: "👩", english: "Mother", local: "Atei" },
            { emoji: "👦", english: "Boy", local: "Kokwet" },
            { emoji: "👧", english: "Girl", local: "Sitet" },
            { emoji: "👴", english: "Grandfather", local: "Kokwet" },
            { emoji: "👵", english: "Grandmother", local: "Atei" },
            { emoji: "👨‍👦", english: "Brother", local: "Ngesen" },
            { emoji: "👩‍👧", english: "Sister", local: "Ngesen" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Ngesen" },
            { emoji: "👶", english: "Baby", local: "Kokwet" },
            { emoji: "🧑", english: "Person", local: "Endulet" },
            { emoji: "👫", english: "Friends", local: "Ngesen" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Asisio" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Koiyok" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Cet" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Taritet" },
            { emoji: "🟡", english: "Yellow", local: "Kipkenyet" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Muet" },
            { emoji: "⚪", english: "White", local: "Buret" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Ang' " },
            { emoji: "2️⃣", english: "Two", local: "Ariyo" },
            { emoji: "3️⃣", english: "Three", local: "Adek" },
            { emoji: "4️⃣", english: "Four", local: "Angwan" },
            { emoji: "5️⃣", english: "Five", local: "Mit" },
            { emoji: "6️⃣", english: "Six", local: "Mot" },
            { emoji: "7️⃣", english: "Seven", local: "Tis" },
            { emoji: "8️⃣", english: "Eight", local: "Sis" },
            { emoji: "9️⃣", english: "Nine", local: "Ong" },
            { emoji: "🔟", english: "Ten", local: "Taman" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Eiyo" },
            { emoji: "👂", english: "Ear", local: "Piné" },
            { emoji: "👃", english: "Nose", local: "Gik" },
            { emoji: "👄", english: "Mouth", local: "Kabii" },
            { emoji: "🦷", english: "Tooth", local: "Kiyo" },
            { emoji: "✋", english: "Hand", local: "Tot" },
            { emoji: "🦶", english: "Foot", local: "Kok" },
            { emoji: "💇", english: "Hair", local: "Kisoi" },
            { emoji: "🧠", english: "Head", local: "Mwiyo" },
            { emoji: "❤️", english: "Heart", local: "Mwoy" }
        ]
    },
    lh: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ng'ombe" },
            { emoji: "🐐", english: "Goat", local: "Emburi" },
            { emoji: "🐔", english: "Chicken", local: "Kuku" },
            { emoji: "🐕", english: "Dog", local: "Isila" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Endwa" },
            { emoji: "🐴", english: "Horse", local: "Farasi" },
            { emoji: "🐟", english: "Fish", local: "Eng'ata" },
            { emoji: "🐘", english: "Elephant", local: "Njogu" },
            { emoji: "🦁", english: "Lion", local: "Imbo" },
            { emoji: "🐊", english: "Crocodile", local: "Mamba" },
            { emoji: "🐒", english: "Monkey", local: "Hosea" },
            { emoji: "🦅", english: "Eagle", local: "Nungu" },
            { emoji: "🐍", english: "Snake", local: "Nhoka" },
            { emoji: "🐸", english: "Frog", local: "Nzingu" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Waĩ" },
            { emoji: "🌽", english: "Maize", local: "Mahindi" },
            { emoji: "🫘", english: "Beans", local: "Nharage" },
            { emoji: "🥔", english: "Potato", local: "Viaswa" },
            { emoji: "🍌", english: "Banana", local: "Ndezu" },
            { emoji: "🥭", english: "Mango", local: "Embe" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tiki" },
            { emoji: "🥛", english: "Milk", local: "Maha" },
            { emoji: "🍞", english: "Bread", local: "Mugate" },
            { emoji: "🥚", english: "Egg", local: "Iyai" },
            { emoji: "🥩", english: "Meat", local: "Inyama" },
            { emoji: "🥜", english: "Groundnuts", local: "Njugu" },
            { emoji: "🥬", english: "Vegetables", local: "Imboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Baba" },
            { emoji: "👩", english: "Mother", local: "Mama" },
            { emoji: "👦", english: "Boy", local: "Mwana" },
            { emoji: "👧", english: "Girl", local: "Mwana" },
            { emoji: "👴", english: "Grandfather", local: "Tata" },
            { emoji: "👵", english: "Grandmother", local: "Makhulu" },
            { emoji: "👨‍👦", english: "Brother", local: "Murwa" },
            { emoji: "👩‍👧", english: "Sister", local: "Murwa" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Mudumba" },
            { emoji: "👶", english: "Baby", local: "Khasulu" },
            { emoji: "🧑", english: "Person", local: "Munhu" },
            { emoji: "👫", english: "Friends", local: "Khandi" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Muzimu" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Mudi" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Ndundu" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Khutio" },
            { emoji: "🟡", english: "Yellow", local: "Khalama" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Ndundu" },
            { emoji: "⚪", english: "White", local: "Khutio" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Imwe" },
            { emoji: "2️⃣", english: "Two", local: "Iri" },
            { emoji: "3️⃣", english: "Three", local: "Tato" },
            { emoji: "4️⃣", english: "Four", local: "Sine" },
            { emoji: "5️⃣", english: "Five", local: "Tano" },
            { emoji: "6️⃣", english: "Six", local: "Mute" },
            { emoji: "7️⃣", english: "Seven", local: "Sanda" },
            { emoji: "8️⃣", english: "Eight", local: "Sane" },
            { emoji: "9️⃣", english: "Nine", local: "Tsivo" },
            { emoji: "🔟", english: "Ten", local: "Kumi" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Liso" },
            { emoji: "👂", english: "Ear", local: "Lulu" },
            { emoji: "👃", english: "Nose", local: "Pũ" },
            { emoji: "👄", english: "Mouth", local: "Khalo" },
            { emoji: "🦷", english: "Tooth", local: "Lino" },
            { emoji: "✋", english: "Hand", local: "Hands" },
            { emoji: "🦶", english: "Foot", local: "Musulu" },
            { emoji: "💇", english: "Hair", local: "Mutsu" },
            { emoji: "🧠", english: "Head", local: "Musulu" },
            { emoji: "❤️", english: "Heart", local: "Mutima" }
        ]
    },
    me: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Ng'ombe" },
            { emoji: "🐐", english: "Goat", local: "Mburi" },
            { emoji: "🐔", english: "Chicken", local: "Kuku" },
            { emoji: "🐕", english: "Dog", local: "Ithuku" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Ngoi" },
            { emoji: "🐴", english: "Horse", local: "Farasi" },
            { emoji: "🐟", english: "Fish", local: "Indu" },
            { emoji: "🐘", english: "Elephant", local: "Njogu" },
            { emoji: "🦁", english: "Lion", local: "Ithwĩ" },
            { emoji: "🐊", english: "Crocodile", local: "Keo" },
            { emoji: "🐒", english: "Monkey", local: "Hosti" },
            { emoji: "🦅", english: "Eagle", local: "Nungu" },
            { emoji: "🐍", english: "Snake", local: "Noka" },
            { emoji: "🐸", english: "Frog", local: "Thingiti" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Mwoko" },
            { emoji: "🌽", english: "Maize", local: "Muhoi" },
            { emoji: "🫘", english: "Beans", local: "Nyoũ" },
            { emoji: "🥔", english: "Potato", local: "Irĩa" },
            { emoji: "🍌", english: "Banana", local: "Ndezu" },
            { emoji: "🥭", english: "Mango", local: "Embe" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tiki" },
            { emoji: "🥛", english: "Milk", local: "Rĩrĩa" },
            { emoji: "🍞", english: "Bread", local: "Mugate" },
            { emoji: "🥚", english: "Egg", local: "Lĩhĩ" },
            { emoji: "🥩", english: "Meat", local: "Nyama" },
            { emoji: "🥜", english: "Groundnuts", local: "Ngroundu" },
            { emoji: "🥬", english: "Vegetables", local: "Mboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Baba" },
            { emoji: "👩", english: "Mother", local: "Maitu" },
            { emoji: "👦", english: "Boy", local: "Mũthondeki" },
            { emoji: "👧", english: "Girl", local: "Mũtheri" },
            { emoji: "👴", english: "Grandfather", local: "Gũkũũ" },
            { emoji: "👵", english: "Grandmother", local: "ũtheri" },
            { emoji: "👨‍👦", english: "Brother", local: "Mũkũũ" },
            { emoji: "👩‍👧", english: "Sister", local: "Mũthondeki" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Mũthenya" },
            { emoji: "👶", english: "Baby", local: "Mũthondeki" },
            { emoji: "🧑", english: "Person", local: "Mũndũ" },
            { emoji: "👫", english: "Friends", local: "Atinga" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Mũthangĩ" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Mũthũrĩrĩ" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Mũthĩmũ" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Mũhĩrĩ" },
            { emoji: "🟡", english: "Yellow", local: "Kĩthĩthĩ" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Mũgũ" },
            { emoji: "⚪", english: "White", local: "Wĩra" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Ĩmwe" },
            { emoji: "2️⃣", english: "Two", local: "Ĩrĩ" },
            { emoji: "3️⃣", english: "Three", local: "Ĩtatu" },
            { emoji: "4️⃣", english: "Four", local: "Ĩnne" },
            { emoji: "5️⃣", english: "Five", local: "Ĩtano" },
            { emoji: "6️⃣", english: "Six", local: "Ĩtandatu" },
            { emoji: "7️⃣", english: "Seven", local: "Ĩnje" },
            { emoji: "8️⃣", english: "Eight", local: "Ĩnane" },
            { emoji: "9️⃣", english: "Nine", local: "Ĩcũma" },
            { emoji: "🔟", english: "Ten", local: "Ĩkũmi" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Irio" },
            { emoji: "👂", english: "Ear", local: "Thĩĩ" },
            { emoji: "👃", english: "Nose", local: "Gĩkũũ" },
            { emoji: "👄", english: "Mouth", local: "Kĩa" },
            { emoji: "🦷", english: "Tooth", local: "Ndira" },
            { emoji: "✋", english: "Hand", local: "Elĩ" },
            { emoji: "🦶", english: "Foot", local: "Guoka" },
            { emoji: "💇", english: "Hair", local: "Gĩthaka" },
            { emoji: "🧠", english: "Head", local: "Rĩĩ" },
            { emoji: "❤️", english: "Heart", local: "Mutwe" }
        ]
    },
    ma: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Enkishu" },
            { emoji: "🐐", english: "Goat", local: "Olpurkel" },
            { emoji: "🐔", english: "Chicken", local: "Endalai" },
            { emoji: "🐕", english: "Dog", local: "Olpai" },
            { emoji: "🐈", english: "Cat", local: "Paka" },
            { emoji: "🐑", english: "Sheep", local: "Olkaptula" },
            { emoji: "🐴", english: "Horse", local: "Olkunono" },
            { emoji: "🐟", english: "Fish", local: "Enkare" },
            { emoji: "🐘", english: "Elephant", local: "Olkejio" },
            { emoji: "🦁", english: "Lion", local: "Olpurung" },
            { emoji: "🐊", english: "Crocodile", local: "Enkere" },
            { emoji: "🐒", english: "Monkey", local: "Enkirei" },
            { emoji: "🦅", english: "Eagle", local: "Enkukut" },
            { emoji: "🐍", english: "Snake", local: "Enok" },
            { emoji: "🐸", english: "Frog", local: "Oloirien" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Wali" },
            { emoji: "🌽", english: "Maize", local: "Olmaka" },
            { emoji: "🫘", english: "Beans", local: "Endulei" },
            { emoji: "🥔", english: "Potato", local: "Olmarosha" },
            { emoji: "🍌", english: "Banana", local: "Enkoromeiyo" },
            { emoji: "🥭", english: "Mango", local: "Mango" },
            { emoji: "🥑", english: "Avocado", local: "Avocado" },
            { emoji: "🍊", english: "Orange", local: "Orange" },
            { emoji: "🍉", english: "Watermelon", local: "Tiki" },
            { emoji: "🥛", english: "Milk", local: "Enk' ajei" },
            { emoji: "🍞", english: "Bread", local: "Mugate" },
            { emoji: "🥚", english: "Egg", local: "Olkejio" },
            { emoji: "🥩", english: "Meat", local: "Enyamun" },
            { emoji: "🥜", english: "Groundnuts", local: "Gunde" },
            { emoji: "🥬", english: "Vegetables", local: "Emboga" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Dedu" },
            { emoji: "👩", english: "Mother", local: "Mama" },
            { emoji: "👦", english: "Boy", local: "Olmurani" },
            { emoji: "👧", english: "Girl", local: "Olpurkel" },
            { emoji: "👴", english: "Grandfather", local: "Kokutai" },
            { emoji: "👵", english: "Grandmother", local: "Naisiae" },
            { emoji: "👨‍👦", english: "Brother", local: "Enkrari" },
            { emoji: "👩‍👧", english: "Sister", local: "Enkrari" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Olpurkel" },
            { emoji: "👶", english: "Baby", local: "Enkrari" },
            { emoji: "🧑", english: "Person", local: "Olmurani" },
            { emoji: "👫", english: "Friends", local: "Enkrari" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Asisio" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Daktari" },
            { emoji: "👨‍🍳", english: "Cook", local: "Enkoiyok" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Olmorit" },
            { emoji: "🔵", english: "Blue", local: "Bluu" },
            { emoji: "🟢", english: "Green", local: "Olmarosha" },
            { emoji: "🟡", english: "Yellow", local: "Olkilain" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Enkishu" },
            { emoji: "⚪", english: "White", local: "Olpaper" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Empewo" },
            { emoji: "2️⃣", english: "Two", local: "Ariyo" },
            { emoji: "3️⃣", english: "Three", local: "Adek" },
            { emoji: "4️⃣", english: "Four", local: "Angwan" },
            { emoji: "5️⃣", english: "Five", local: "Tie" },
            { emoji: "6️⃣", english: "Six", local: "Tarago" },
            { emoji: "7️⃣", english: "Seven", local: "Sot" },
            { emoji: "8️⃣", english: "Eight", local: "Siet" },
            { emoji: "9️⃣", english: "Nine", local: "Ong' " },
            { emoji: "🔟", english: "Ten", local: "Tom" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Enkai" },
            { emoji: "👂", english: "Ear", local: "Purana" },
            { emoji: "👃", english: "Nose", local: "Enkoi" },
            { emoji: "👄", english: "Mouth", local: "Oloshoo" },
            { emoji: "🦷", english: "Tooth", local: "Endulei" },
            { emoji: "✋", english: "Hand", local: "Ellelo" },
            { emoji: "🦶", english: "Foot", local: "Enguke" },
            { emoji: "💇", english: "Hair", local: "Enkioyio" },
            { emoji: "🧠", english: "Head", local: "Olopapash" },
            { emoji: "❤️", english: "Heart", local: "Olobilili" }
        ]
    },
    so: {
        animals: [
            { emoji: "🐄", english: "Cow", local: "Sac" },
            { emoji: "🐐", english: "Goat", local: "Rari" },
            { emoji: "🐔", english: "Chicken", local: "Diga" },
            { emoji: "🐕", english: "Dog", local: "Eey" },
            { emoji: "🐈", english: "Cat", local: "Bisad" },
            { emoji: "🐑", english: "Sheep", local: "Ido" },
            { emoji: "🐴", english: "Horse", local: "Faras" },
            { emoji: "🐟", english: "Fish", local: "Kalluun" },
            { emoji: "🐘", english: "Elephant", local: "Maroodi" },
            { emoji: "🦁", english: "Lion", local: "Libaax" },
            { emoji: "🐊", english: "Crocodile", local: "Doyaal" },
            { emoji: "🐒", english: "Monkey", local: "Daanyi" },
            { emoji: "🦅", english: "Eagle", local: "Shimbir" },
            { emoji: "🐍", english: "Snake", local: "Maran" },
            { emoji: "🐸", english: "Frog", local: "Rah" }
        ],
        food: [
            { emoji: "🍚", english: "Rice", local: "Bariis" },
            { emoji: "🌽", english: "Maize", local: "Galley" },
            { emoji: "🫘", english: "Beans", local: "Digir" },
            { emoji: "🥔", english: "Potato", local: "Bataato" },
            { emoji: "🍌", english: "Banana", local: "Muus" },
            { emoji: "🥭", english: "Mango", local: "Cambo" },
            { emoji: "🥑", english: "Avocado", local: "Avacado" },
            { emoji: "🍊", english: "Orange", local: "Liin" },
            { emoji: "🍉", english: "Watermelon", local: "Taaw" },
            { emoji: "🥛", english: "Milk", local: "Caano" },
            { emoji: "🍞", english: "Bread", local: "Rooti" },
            { emoji: "🥚", english: "Egg", local: "Ukun" },
            { emoji: "🥩", english: "Meat", local: "Hilib" },
            { emoji: "🥜", english: "Groundnuts", local: "Lox" },
            { emoji: "🥬", english: "Vegetables", local: "Maraq" }
        ],
        family: [
            { emoji: "👨", english: "Father", local: "Aabe" },
            { emoji: "👩", english: "Mother", local: "Hooyo" },
            { emoji: "👦", english: "Boy", local: "Wiil" },
            { emoji: "👧", english: "Girl", local: "Gabar" },
            { emoji: "👴", english: "Grandfather", local: "Awoowe" },
            { emoji: "👵", english: "Grandmother", local: "Eddo" },
            { emoji: "👨‍👦", english: "Brother", local: "Walaalo" },
            { emoji: "👩‍👧", english: "Sister", local: "Walaalo" },
            { emoji: "👨‍👩‍👦", english: "Family", local: "Qoys" },
            { emoji: "👶", english: "Baby", local: "Ilmo" },
            { emoji: "🧑", english: "Person", local: "Qof" },
            { emoji: "👫", english: "Friends", local: "Saaxiib" },
            { emoji: "👨‍🏫", english: "Teacher", local: "Macallin" },
            { emoji: "👩‍⚕️", english: "Doctor", local: "Dhakhtar" },
            { emoji: "👨‍🍳", english: "Cook", local: "Karintoiye" }
        ],
        colors: [
            { emoji: "🔴", english: "Red", local: "Cas" },
            { emoji: "🔵", english: "Blue", local: "Buluug" },
            { emoji: "🟢", english: "Green", local: "Cagaar" },
            { emoji: "🟡", english: "Yellow", local: "Huruud" },
            { emoji: "🟠", english: "Orange", local: "Orange" },
            { emoji: "🟣", english: "Purple", local: "Purple" },
            { emoji: "⚫", english: "Black", local: "Madow" },
            { emoji: "⚪", english: "White", local: "Cad" },
            { emoji: "🟤", english: "Brown", local: "Brown" },
            { emoji: "💗", english: "Pink", local: "Pink" }
        ],
        numbers: [
            { emoji: "1️⃣", english: "One", local: "Kow" },
            { emoji: "2️⃣", english: "Two", local: "Laba" },
            { emoji: "3️⃣", english: "Three", local: "Saddex" },
            { emoji: "4️⃣", english: "Four", local: "Afar" },
            { emoji: "5️⃣", english: "Five", local: "Shan" },
            { emoji: "6️⃣", english: "Six", local: "Lix" },
            { emoji: "7️⃣", english: "Seven", local: "Toddoba" },
            { emoji: "8️⃣", english: "Eight", local: "Siddeed" },
            { emoji: "9️⃣", english: "Nine", local: "Sagaal" },
            { emoji: "🔟", english: "Ten", local: "Toban" }
        ],
        body: [
            { emoji: "👁️", english: "Eye", local: "Indho" },
            { emoji: "👂", english: "Ear", local: "Dheg" },
            { emoji: "👃", english: "Nose", local: "San" },
            { emoji: "👄", english: "Mouth", local: "Af" },
            { emoji: "🦷", english: "Tooth", local: "Ilko" },
            { emoji: "✋", english: "Hand", local: "Gacan" },
            { emoji: "🦶", english: "Foot", local: "Lug" },
            { emoji: "💇", english: "Hair", local: "Timaha" },
            { emoji: "🧠", english: "Head", local: "Madax" },
            { emoji: "❤️", english: "Heart", local: "Wadne" }
        ]
    }
};

const CATEGORY_INFO = {
    animals: { name: "Animals", emoji: "🐄" },
    food: { name: "Food", emoji: "🍚" },
    family: { name: "Family", emoji: "👨‍👩‍👧" },
    colors: { name: "Colors", emoji: "🎨" },
    numbers: { name: "Numbers", emoji: "🔢" },
    body: { name: "Body Parts", emoji: "🦶" }
};
